title: NAGENDRA TANIKELLA
url: "https://ngtanikella.github.io"
baseurl: ""

description: Nagendra Tanikella's website

markdown: kramdown

google_analytics_tracking_id: G-HDP93TMLT1

sass:
    style: compressed
    sass_dir: _sass

include: ["_pages"]

google_scholar_url:   https://scholar.google.com/citations?user=ZwY-zMgAAAAJ&hl=en&oi=ao
github_username:      ngtanikella
linkedin_username:    nagendra-tanikella
